name: Simple Gatekeeper Test

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch: # يتيح لك تشغيله يدوياً بضغطة زر

jobs:
  dummy_check_job:
    name: "Quality Gate Check" # هذا هو الاسم الذي ستجده في الإعدادات
    runs-on: ubuntu-latest
    steps:
      - name: Run Dummy Test
        run: |
          echo "Running simple health check..."
          echo "Success!"
          exit 0
